### ISSUE TITLE
Load model multiple times

### ISSUE THREAD

**Issue by VoThanhDanh95** [yuanyuanli85/Keras-Multiple-Process-Prediction#3]
Hi guys.
I really appreciate your project. It helps me a lot.
But I have a problem here. In my case, my img_path folder changes all the time.
Take example, at first I load all the images in that folder to predict using your code.
During predicting time, more and more images update to that folder and I have to predict again after finish the previous step.
So the problem is that I have to load model again after finish 1 step. Is there any way to load model only one times ?
Thank you in advance

**Comment by yuanyuanli85** [comment]
Close this issue since we have synced via email.   The proven idea is to let Scheduler() does dynamic scan and pushes the new images to the queue, and the workers can fetch data from the queue and process it.
