### ISSUE TITLE
Get result for all the files 

### ISSUE THREAD

**Issue by mit456** [yuanyuanli85/Keras-Multiple-Process-Prediction#4]
Hello,

Thanks for the project, I tried to implement in my project and it works but one issue I am facing and its very silly.

how do I get the output for all the images present in `imagepath` from `vgg16_worker` to `main` program after  `worker.join`? I tried a couple of options I mean creating a `result_queue` and put the outputs there but the queue is having result of the only one image.

**Comment by TCherici** [comment]
have you tried passing the extra queue as argument for the initiation of each worker, and add each prediction to the queue directly?

**Comment by mit456** [comment]
You mean here [Line17](https://github.com/yuanyuanli85/Keras-Multiple-Process-Prediction/blob/master/main.py#L17)
Yes, I did try that. Did not work the same result I mean only single result to in the queue.
