### ISSUE TITLE
How to adopt this code in multiprocessing CPU instead of GPU

### ISSUE THREAD

**Issue by iamgmujtaba** [yuanyuanli85/Keras-Multiple-Process-Prediction#7]
Hi,
Thank you for this wonderful example. Please guide me how I can adopt this code in multiple CPU for prediction. 

Thanks,

**Comment by YKritet** [comment]
Same here,

Thanks in advance

**Comment by yuanyuanli85** [comment]
As I know, keras will utilize multiple cores via backend tf. User don't need to schedule them explicitly.
